#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'WRENStatusMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 8

# The Active Message type associated with this message.
AM_TYPE = 112

class WRENStatusMsg(tinyos.message.Message.Message):
    # Create a new WRENStatusMsg of size 8.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=8):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <WRENStatusMsg> \n"
        try:
            s += "  [src=0x%x]\n" % (self.get_src())
        except:
            pass
        try:
            s += "  [sensing=0x%x]\n" % (self.get_sensing())
        except:
            pass
        try:
            s += "  [buffersize=0x%x]\n" % (self.get_buffersize())
        except:
            pass
        try:
            s += "  [download=0x%x]\n" % (self.get_download())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: src
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'src' is signed (False).
    #
    def isSigned_src(self):
        return False
    
    #
    # Return whether the field 'src' is an array (False).
    #
    def isArray_src(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'src'
    #
    def offset_src(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'src'
    #
    def offsetBits_src(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'src'
    #
    def get_src(self):
        return self.getUIntElement(self.offsetBits_src(), 16, 1)
    
    #
    # Set the value of the field 'src'
    #
    def set_src(self, value):
        self.setUIntElement(self.offsetBits_src(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'src'
    #
    def size_src(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'src'
    #
    def sizeBits_src(self):
        return 16
    
    #
    # Accessor methods for field: sensing
    #   Field type: short
    #   Offset (bits): 16
    #   Size (bits): 8
    #

    #
    # Return whether the field 'sensing' is signed (False).
    #
    def isSigned_sensing(self):
        return False
    
    #
    # Return whether the field 'sensing' is an array (False).
    #
    def isArray_sensing(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sensing'
    #
    def offset_sensing(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'sensing'
    #
    def offsetBits_sensing(self):
        return 16
    
    #
    # Return the value (as a short) of the field 'sensing'
    #
    def get_sensing(self):
        return self.getUIntElement(self.offsetBits_sensing(), 8, 1)
    
    #
    # Set the value of the field 'sensing'
    #
    def set_sensing(self, value):
        self.setUIntElement(self.offsetBits_sensing(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sensing'
    #
    def size_sensing(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'sensing'
    #
    def sizeBits_sensing(self):
        return 8
    
    #
    # Accessor methods for field: buffersize
    #   Field type: long
    #   Offset (bits): 24
    #   Size (bits): 32
    #

    #
    # Return whether the field 'buffersize' is signed (False).
    #
    def isSigned_buffersize(self):
        return False
    
    #
    # Return whether the field 'buffersize' is an array (False).
    #
    def isArray_buffersize(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'buffersize'
    #
    def offset_buffersize(self):
        return (24 / 8)
    
    #
    # Return the offset (in bits) of the field 'buffersize'
    #
    def offsetBits_buffersize(self):
        return 24
    
    #
    # Return the value (as a long) of the field 'buffersize'
    #
    def get_buffersize(self):
        return self.getUIntElement(self.offsetBits_buffersize(), 32, 1)
    
    #
    # Set the value of the field 'buffersize'
    #
    def set_buffersize(self, value):
        self.setUIntElement(self.offsetBits_buffersize(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'buffersize'
    #
    def size_buffersize(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'buffersize'
    #
    def sizeBits_buffersize(self):
        return 32
    
    #
    # Accessor methods for field: download
    #   Field type: short
    #   Offset (bits): 56
    #   Size (bits): 8
    #

    #
    # Return whether the field 'download' is signed (False).
    #
    def isSigned_download(self):
        return False
    
    #
    # Return whether the field 'download' is an array (False).
    #
    def isArray_download(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'download'
    #
    def offset_download(self):
        return (56 / 8)
    
    #
    # Return the offset (in bits) of the field 'download'
    #
    def offsetBits_download(self):
        return 56
    
    #
    # Return the value (as a short) of the field 'download'
    #
    def get_download(self):
        return self.getUIntElement(self.offsetBits_download(), 8, 1)
    
    #
    # Set the value of the field 'download'
    #
    def set_download(self, value):
        self.setUIntElement(self.offsetBits_download(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'download'
    #
    def size_download(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'download'
    #
    def sizeBits_download(self):
        return 8
    
